### ISSUE TITLE
Bug: Crash on Enable

### ISSUE THREAD

**Issue by iisacc** [ThioJoe/Dynamic-Lighting-Key-Indicator#4]
I have a Logitech G512, Windows 11.
The app installed, and runs, but crashes instantly when I click "Enable".
Total crash to desktop, no log files, so zero clues why.

**Comment by ThioJoe** [comment]
It _might_ put a crash log in your TEMP directory (Accessible by typing `%TEMP%` into Explorer) called `Dynamic_Lighting_Key_Indicator_Crash_Log.txt` (or at least it's supposed to).

**Comment by iisacc** [comment]
Nice, it's there.

My guess is it's looking for you, not me? ( D:\Users\Joe\... )

This is the log:

```
Timestamp: 24/12/2024 5:06:48 AM
Message: An item with the same key has already been added. Key: :REDACTED:
Exception: System.ArgumentException: An item with the same key has already been added. Key: :REDACTED:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Stack Trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Source: System.Private.CoreLib
Target Site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
```

**Comment by Dark-AltF8** [comment]
I am getting the same issue, although I am using a Razer keyboard. It does look like it is looking for the Joe document directory and not the users.


```
Timestamp: Monday, December 23 2024 12:47:08
Message: An item with the same key has already been added. Key: 6acf63e6-bab5-11ef-a558-806e6f6e6963
Exception: System.ArgumentException: An item with the same key has already been added. Key: 6acf63e6-bab5-11ef-a558-806e6f6e6963
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Stack Trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dynamic_Lighting_Key_Indicator.MainWindow.FindKeyboardLampArrayDevices() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 72
   at Dynamic_Lighting_Key_Indicator.MainWindow.GetKeyboardLampArrayDeviceSelectorAsync() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\Handlers\LightingDeviceHandling.cs:line 98
   at Dynamic_Lighting_Key_Indicator.MainWindow.StartWatchingForLampArrays() in D:\Users\Joe\Documents\Development\Dynamic-Lighting-Key-Indicator\MainWindow.xaml.cs:line 268
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
Source: System.Private.CoreLib
Target Site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)

```

**Comment by ThioJoe** [comment]
By any chance is your keyboard the wireless version? Or alternatively is your keyboard plugged into a usb hub?

**Comment by iisacc** [comment]
Wired G512, no hub, directly to rear usb port.

**Comment by Dark-AltF8** [comment]
For me it is a wired keyboard.

**Comment by ThioJoe** [comment]
It might be that Windows added a duplicate entry if it was ever plugged into a different port or something. I can add some handling but might not be able to until the weekend. 

In the meantime you could try seeing if the device shows up as an old unused device in the device manager as a "hidden device" and remove it. 

Apparently there's a tool called "Device Cleanup Tool" that might be worth trying, assuming that's the issue, though I don't know much about it.

**Comment by iisacc** [comment]
Checked Device Manager, no hidden/unused devices. 
Created restore point, then ran Device Cleanup Tool as Administrator, deleted all the old entries.
Reboot, retry, still crashes to desktop.
I even searched the Registry for the item key listed in the log, but didn't find anything here.

**Comment by ThioJoe** [comment]
Alright I'll just have to look into it

**Comment by RexLuscus56** [comment]
Just to add  a 'me too' to this issue, which appears to be similar to issue #2. I'm using a wired G513, and my crash log is identical to those posted, but (obvs) with a different device GUID. There do appear to be hard-coded paths in the stack trace, but I don't know enough to say if this is the cause of, or contributes to, the CTD.

**Comment by ThioJoe** [comment]
The paths in the stack trace aren't related I don't think. Just some constant the compiler stored

Anyway @philkark was able to find a workaround by finding the device which had the same container ID and removing it. This may or may not work depending on the system I think, like if the keyboard legitimately has two interfaces that use the same container id: https://github.com/ThioJoe/Dynamic-Lighting-Key-Indicator/issues/2#issuecomment-2560467222

**Comment by RexLuscus56** [comment]
Thanks for the response. In my case the device which upsets the program is a SteelSeries Aerox mouse.  Even if I remove all instances in Device Manager and remove the USB dongle with no SteelSeries software running, the next hardware scan replaces both instances under the 'keyboards' section and causes the app to throw an exception.

**Comment by ThioJoe** [comment]
I just posted a new version 1.0.1 which MIGHT fix it.

I can't actually properly test how it works myself though so I'm marking it as pre-release for now until it's confirmed working: https://github.com/ThioJoe/Dynamic-Lighting-Key-Indicator/releases/tag/v1.0.1

**Comment by iisacc** [comment]
After a bit of testing with 1.0.0 and 1.0.1 I have some findings for you.

Device Manager lists 4 HID Keyboard Devices.
The first two have identical "Base container ID", The 3rd and 4th have unique IDs.
So I manually removed the duplicate device. (Note, this automatically re-installs upon scan for hardware changes and if I reboot.)
![1-Duplicates](https://github.com/user-attachments/assets/8c27b074-4af6-4058-bfeb-365208b233ea)
![2-DupeRemoved](https://github.com/user-attachments/assets/b6fdfc4a-1b00-4f0a-8cdd-77cae029e052)

Using 1.0.1 I can now "Enable", however there's nothing in the selection box, it's just blank.
So, Going back to 1.0.0 I can again "Enable" AND the G512 is in the list! 
However, the colours in the keyboard are all messed up.

Pre-Enable
![3-No-DLK](https://github.com/user-attachments/assets/e35e671f-04bf-4963-8429-8c996e762b0b)

Post Enable- On
![4-DLK-on](https://github.com/user-attachments/assets/0732cc22-1e0d-4cfa-ae12-f361a68adb32)

Post Enable-Off
![5-DLK-off](https://github.com/user-attachments/assets/1796920f-a8e7-4e1c-b235-f4928e49fbc0)

**Comment by ThioJoe** [comment]
It's not really unexpected for some devices to have the same container ID, it's actually the point of the container id. I just wasn't handling it properly.

Try 1.0.1.1 it should fix the issue of no devices showing up. It's attach to the same pre-release post.

**Comment by iisacc** [comment]
1.0.1.1 Now works, even with the duplicated Base container ID!

Only issue remaining for me is the colouring.

**Comment by ThioJoe** [comment]
~~What's the problem with the coloring 🤔~~
Edit: oh you meant the same as the post above. 

Not really sure what could be causing that. If the keyboard appears multiple times in the list maybe try a different one? Or also if so see if maybe the keys that are the wrong color are different depending on which one is selected?

**Comment by iisacc** [comment]
Only one G512 in the list.
With a little further testing, SCRLK and NUM, when pressed, each affect the other buttons colour also. (Button function remains.)
Then using CAPS toggles both SCRLK and NUM's colours.
The two colours on the rest of the keys are the apps two colours. Pressing any of the 3 activator keys toggles roughly half the coloured regular keys to flip too. (As seen in the images prior.)

:edit: 
I've also checked the Logitech software to ensure it's setup to pass colouring to windows.

**Comment by ThioJoe** [comment]
Ok anyway I think the crashing is fixed, and there's also a new version 1.1.0 which has improved debug logging options if it still does.
